const actionTypes = Object.freeze({
  //auth
  GET_ROLES_START: "GET_ROLES_START",
  GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
  GET_ROLES_FAILED: "GET_ROLES_FAILED",

  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILED: "ADD_USER_FAILED",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  GET_ADMIN_BOARD_START: "GET_ADMIN_BOARD_START",
  GET_ADMIN_BOARD_SUCCESS: "GET_ADMIN_BOARD_SUCCESS",
  GET_ADMIN_BOARD_FAILED: "GET_ADMIN_BOARD_FAILED",

  GET_MODERATOR_BOARD_START: "GET_MODERATOR_BOARD_START",
  GET_MODERATOR_BOARD_SUCCESS: "GET_MODERATOR_BOARD_SUCCESS",
  GET_MODERATOR_BOARD_FAILED: "GET_MODERATOR_BOARD_FAILED",

  GET_USER_BOARD_START: "GET_USER_BOARD_START",
  GET_USER_BOARD_SUCCESS: "GET_USER_BOARD_SUCCESS",
  GET_USER_BOARD_FAILED: "GET_USER_BOARD_FAILED",

  UPDATE_ACCESS_TOKEN: "UPDATE_ACCESS_TOKEN",
});

export default actionTypes;
